name: installmaven
on: [worklow_dispatch]

jobs:
  install maven
    run-on: self-hosted
    steps:
      - name: install java
        run: sudo yum install java -y
      - name: install maven
        run: sudo yum install maven -y
  